name: Deploy to VPS

on:
  push:
    branches:
      - main # ou master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Copy files to VPS
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "." # Copia todo o conteúdo do repositório
          target: "/root/anjos-anonimos" # Para este diretório no servidor

      # --- PASSO DE DEBUG ---
      - name: Verify docker-compose.yml on VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            echo "--- Verificando /root/anjos-anonimos/docker-compose.yml ---"
            cat /root/anjos-anonimos/docker-compose.yml # Mostra o conteúdo do compose no servidor
            echo "--- Fim da verificação ---"
      # --- FIM DO PASSO DE DEBUG ---

      - name: Deploy to VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /root/anjos-anonimos # Entra no diretório correto
            docker-compose down --remove-orphans # Para e remove containers antigos deste compose
            docker system prune -f # Limpa recursos não usados do Docker (containers parados, etc)
            docker-compose up -d --build # Constrói a imagem e sobe os containers em background